Delay Calibration Scripts
=========================

applySelfCalTBW2.py
------------------
Given a FITS IDI file generated by correlateTBW.py that contains all valid 
dipoles and both polarizations perform a phase-only self-calibration on the
long baselines using a simple point source model of the sky.

checkConsistency.py
-------------------
Given a collection of .sc files generated by applySelfCalTBW2.py create a plot
of the delay for each antenna over time and combine the various files into a
master delay file called 'merged.delays'.

convertDelayToStretch.py
------------------------
Given a reference SSMIF and a .sc file generated by applySelfCalTBW2.py or the 
'merged.delays' files from checkConsistency.py, convert the delays in ns to stretch 
factors.

applyNewStretchFactors.py
-------------------------
Given an input SSMIF and a collection of stretch factors from 
convertDelayToStretch.py, apply the new stretch factors and create a new SSMIF.

estimateSEFD.py
---------------
Given an SSMIF and a collection of TBW files, use the SoftwareDP to form beams at 
the transit point of a source and estimate the system equivalent flux density (SEFD) 
and pointing error.

fitEstimatedSEFD.py
-------------------
Fit a Gaussian to the results of estimateSEFD.py to determined the SEFD and pointing 
error.
